### ISSUE TITLE
"Access to the path '/home/[redacted]/Projects/mkds/mods/n64toad/output' is denied." error

### ISSUE THREAD

**Issue by Bloxxel64** [haroohie-club/NitroPacker#12]
pretty much what it says on the tin. upon trying to repack a rom i get said error, here is the command and full console output

```
$ ./NitroPacker pack  -o /home/[redacted]/Projects/mkds/mods/n64toad/output -p /home/[redacted]/Projects/mkds/mods/n64toad/gamedata/n64toadsfx.xml

Unhandled exception. System.UnauthorizedAccessException: Access to the path '/home/[redacted]/Projects/mkds/mods/n64toad/output' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at HaroohieClub.NitroPacker.Core.NdsProjectFile.Pack(String outputRomPath, String projectFilePath, Boolean compressArm9)
   at HaroohieClub.NitroPacker.Cli.PackCommand.Invoke(IEnumerable`1 arguments)
   at Mono.Options.CommandSet.Run(IEnumerable`1 arguments)
   at HaroohieClub.NitroPacker.Cli.Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by Bloxxel64** [comment]
turns out i am an idiot and didn't add the name of the file to the output path smh.
